name: Test modified scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout generator repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Test modified and new scripts
        run: |
          chmod +x tests/execute_new_and_modified_scripts.sh
          sudo tests/execute_new_and_modified_scripts.sh
          exit $?